[versions]
agp = "8.12.0"
kotlin = "2.0.0"
androidxCore = "1.13.1"
androidxLifecycle = "2.9.2"
androidxActivity = "1.10.1"
compose-bom = "2024.06.00" ## if you don't want to manage a set of depenencies, you can manage a bom and then you won't need the to provide the verion ref
androidxTestJunit = "1.2.1"
espresso = "3.5.1"
junit = "4.13.2"
hilt = "2.51.1"
coroutines = "1.10.2"
ksp =  "2.0.0-1.0.21"
retrofit = "2.10.0"
okHttp = "4.12.0"
kotlinxSerializationJson = "1.7.1"
kotlinxImmutable = "0.4.0"
androidxHiltNavigationCompose = "1.2.0"
appcompat = "1.7.1"
material = "1.13.0"
androidxRoom = "2.7.2"
coil = "2.5.0"
androidxNavigation = "2.7.7"
mockk = "1.14.0"



[libraries]
# android
androidx-core = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCore" }
androidx-lifecycle-viewModelCompose = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-compose", version.ref = "androidxLifecycle" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycle" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "androidxActivity" }
androidx-compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui"}
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics"}
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview"}
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3"}
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxTestJunit" }
androidx-espresso = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4"}
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest"}
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidxRoom" }
coil-compose = {group = "io.coil-kt", name = "coil-compose", version.ref = "coil" }
coil-gif = {group = "io.coil-kt", name = "coil-gif", version.ref = "coil" }
coil-video = {group = "io.coil-kt", name = "coil-video", version.ref = "coil" }
androidx-compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }

# coroutines
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }

# depency injection (hilt)
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

# networking (retrofit, okhttp, serialization)
retrofit-bom = { module = "com.squareup.retrofit2:retrofit-bom", version.ref = "retrofit" }
retrofit = { module = "com.squareup.retrofit2:retrofit" }
retrofit-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization" }
okhttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okHttp" }
kotlinx-immutable-collection = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinxImmutable" }
okhttp-logging = { group="com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okHttp" }

# unit testing
junit = { module = "junit:junit", version.ref = "junit" }
mockk = {module ="io.mockk:mockk", version.ref = "mockk"}

# other stuff
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-plugin = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }